# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created

name: Publich Npm Package

on:
  release:
    types: [published, released, created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g pnpm

      - run: pnpm install
      - run: pnpm build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
